# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'FindNine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FindNine
pod 'DateToolsSwift'
pod 'ReachabilitySwift'
pod 'SDWebImage'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # 强制所有 pods 至少使用 iOS 12
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end

end
